### ISSUE TITLE
Allowing specific armors around the no flight ban

### ISSUE THREAD

**Issue by Cazadorsniper** [quat1024/BrokenWings#1]
Is it possible to allow specific armors like draconic, multi and Infinity to give the player flight even in broken winged dimensions?

**Comment by quat1024** [comment]
This is a good idea, I'll look into it

**Comment by quat1024** [comment]
Ok, in the next update, you will be able to specify item IDs in the config file that will whitelist players from the no-flight rule.

You can separately specify item IDs that players need to wear as armor to bypass the rule, and item IDs that players can just have anywhere in their inventory to bypass the rule (like an Angel Ring, but in reverse)

**Comment by quat1024** [comment]
oh, and one more thing, there's also (an option to enable) a tooltip that communicates this item whitelist to the player:
![image](https://user-images.githubusercontent.com/2068021/53781078-3df60400-3ed5-11e9-9d76-615162e0d1e3.png)
it turns green when the player's in a dimension that ordinarily they would not be able to fly in, and red otherwise

**Comment by quat1024** [comment]
Approved now as version 2.0, hope you enjoy
